replicaCount: 1

image:
  repository: gcr.io/google-samples/gb-frontend
  tag: v5
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    argocd.argoproj.io/compare-result: "true"
  path: /
  hosts:
    - guestbook.domain.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
